### ISSUE TITLE
Gathernd Layer with input type float and indices int16 is creating Flex layer 

### ISSUE THREAD

**Issue by gokulmanoj510** [PINTO0309/onnx2tf#187]
### Issue Type

Others

### onnx2tf version number

1.5.31

### onnx version number

1.12.0

### tensorflow version number

2.11.0

### Download URL for ONNX

nil

### Parameter Replacement JSON

```json
nil
```

### Description

Purpose : Personal development
I am trying to convert a model from onnx to tensorflow. There is a gathernd layer in my model. If i give input as float and indices as int32. it is converting properly. whereas if i use input as float and indices as int16. Atfer conversion it is producing flex layers. as shown in the below image.
![image](https://user-images.githubusercontent.com/21981252/218408148-48977d28-d74e-46b5-a5c0-6b3b2d1983b7.png)
Is there any way to solve the issue.

**Comment by PINTO0309** [comment]
You don't have to share the entire ONNX model, but can you provide a partial ONNX model of the part that raises the question?

Since I create these tools as a hobby in my personal time, I have limited time to devote to the research. Your cooperation would be greatly appreciated. :)

**Comment by Hyunseok-Kim0** [comment]
This is pretty normal thing in tflite. The builtin operators have many constraints, and data type is one of them. As you see in the official document of tensorflow, `gather_nd` supports int32 and int64 as data type for indices. https://www.tensorflow.org/api_docs/python/tf/gather_nd
Also, I guess `Add` is converted to `FlexAddV2` because the data type between two operands are not matched, or may not supported in builtin operator.
I recommend you to use quantization if you just want to reduce the size of model by reducing bits of numbers.
