### ISSUE TITLE
[ssdlite320_mobilenet_v3_large] Cannot reshape a tensor with 41835024 elements to shape [3234,4] (12936 elements)

### ISSUE THREAD

**Issue by TaylorHere** [PINTO0309/onnx2tf#217]
### Issue Type

Others

### onnx2tf version number

1.7.10

### onnx version number

1.12.0

### tensorflow version number

2.11.0

### Download URL for ONNX

[ssdlite320_mobilenet_v3_large.zip](https://github.com/PINTO0309/onnx2tf/files/10862467/ssdlite320_mobilenet_v3_large.zip)

> 

### Parameter Replacement JSON

```json
{}
```

### Description

1. I'm trying to convert an onnx model(ssdlite320_mobilenet_v3_large) comes from [torchvision](https://pytorch.org/vision/main/models/generated/torchvision.models.detection.ssdlite320_mobilenet_v3_large.html#torchvision.models.detection.ssdlite320_mobilenet_v3_large) into tensorflow model
2. here is the log: https://logpaste.com/WdRLSuFg
3. the shape `[1,3234,4,3234]` of the `flatten`  is wried, in ONNX model is `[3234, 1]`, so I try to find where the wried shape comes from, then I notice that the `/Split` op has wrong output shape  `[1,3,320,320]` , it should be `[1,3234,4]` , and the wrong shape `[1,3,320,320]` may come from op `/transform/Split`
 
![图片](https://user-images.githubusercontent.com/12156543/222179812-1a90bb0b-7047-43ea-9fe5-31368af3d1f3.png)

![图片](https://user-images.githubusercontent.com/12156543/222178827-0e0a8e73-6828-4e75-ab8d-cda5b780138c.png)
![图片](https://user-images.githubusercontent.com/12156543/222178968-3af5d111-3a62-4429-bb8a-0656bf08e120.png)

**Comment by PINTO0309** [comment]
[ssdlite320_mobilenet_v3_large_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/10862979/ssdlite320_mobilenet_v3_large_float32.tflite.zip)

Most TorchVision models are not recommended because their structure is often very redundant and broken.

Once the regression test for the above pull request is all green I will release a modified version. (Fastest is in 30 minutes)

**Comment by TaylorHere** [comment]
thx for your advice and fast response

**Comment by PINTO0309** [comment]
Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.7.11

**Comment by PINTO0309** [comment]
Improved overall process by adding a process to suppress `FlexSplitV` generation.
https://github.com/PINTO0309/onnx2tf/releases/tag/1.7.12

**Comment by zeyad-kay** [comment]
@TaylorHere How did you convert to onnx? I have an onnx model exported using ```torch.onnx.export``` and is working fine but when trying to convert to tflite, the conversion and graphs are correct but when I start inference it crashes due to incompatible shapes at an ```Add``` node.

I suspect it is an onnx problem because I managed to convert your model and do inference. Both graphs look identical to me but I guess I am missing something.
