### ISSUE TITLE
[Faster R-CNN] Faster R-CNN without nms error issue

### ISSUE THREAD

**Issue by FrankZTH** [PINTO0309/onnx2tf#309]
### Issue Type

Others

### onnx2tf version number

1.9.1

### onnx version number

1.13.1

### tensorflow version number

2.8.0

### Download URL for ONNX

https://drive.google.com/file/d/1O_4DgH6UvSEq-t0nADhFvcbIxPUhx00s/view?usp=sharing

### Parameter Replacement JSON

```json
none
```

### Description

1. Our research. The graduation project need.
2. The output bounding boxes are not correct.
3. I tried to convert the pytorch's faster-rcnn to tensorflow, originally there are some issue occurs at padding and nms operations, I removed theses operation in the model architecture and there are still have some error in rcnn head.
The rcnn output return "unmatched"
4. Graduation Project need.

**Comment by PINTO0309** [comment]
I have already issued a pull request.

**Comment by PINTO0309** [comment]
update: v1.9.2

It can now be converted successfully.

![image](https://user-images.githubusercontent.com/33194443/231423630-7ce311c5-22fb-4242-a89f-a64b3b2adb80.png)

If you are referring to `Unmatched` errors, try to ignore the results of accuracy checks after operations where the number of outputs is an unspecified number. Verification of the output accuracy of the Mask R-CNN to which the post-processing is connected is in principle impossible with onnx2tf. The use of the `NonZero` operation is undesirable.

![image](https://user-images.githubusercontent.com/33194443/231424167-ae5b7897-5d70-4ec1-a96a-5c4f024bb919.png)

![image](https://user-images.githubusercontent.com/33194443/231425194-b7a3acc2-9466-423a-af51-8cd168a34eda.png)

**Comment by FrankZTH** [comment]
Ok... I knew.
Sorry for another question, I want to export the .H5 file to tensorflow retrain.
But it run out an error like this.
![Screenshot from 2023-04-13 09-39-05](https://user-images.githubusercontent.com/25993710/231624171-90ed199a-f2af-495b-8be1-647ba92e6b05.png)

**Comment by PINTO0309** [comment]
Keras .h5 is an old format that is not even officially recommended by TensorFlow. Even if the model is converted successfully, Keras issues can cause errors. Keras internal problems cannot be addressed by onnx2tf.

Use `-osd` or `-okv3` or `-otfv1pb`.

```
Unable to serialize [23 40] to JSON. Unrecognized type <class 'tensorflow.python.framework.ops.EagerTensor'>.
  File "/home/xxxxx/git/onnx2tf/onnx2tf/onnx2tf.py", line 850, in convert
    model.save(f'{output_folder_path}/{output_file_name}_float32.h5')
  File "/home/xxxxx/git/onnx2tf/onnx2tf/onnx2tf.py", line 2032, in main
    model = convert(
  File "/home/xxxxx/git/onnx2tf/onnx2tf/onnx2tf.py", line 2082, in <module>
    main()
TypeError: Unable to serialize [23 40] to JSON. Unrecognized type <class 'tensorflow.python.framework.ops.EagerTensor'>.
```

**Comment by FrankZTH** [comment]
I had a question about the unmatched issue during the conversion. Seems like if I prevent the nonzero operation, the unmatched issue could be prevented. So I modified the ROI Align to prevent such operation, but the unmatched issue still occurs.

![Screenshot from 2023-04-13 11-36-35](https://user-images.githubusercontent.com/25993710/231642862-44e3b6a1-d61f-4624-a21f-39b33f42ab0f.png)


The unmatched issue started from multiplication operator which is a operation that I didn't expected to creates issue.

**Comment by PINTO0309** [comment]
Internally, onnx2tf tries to optimize the redundant operations of ONNX as much as possible. Thus, it frequently happens that two or more OPs that were unnecessary in ONNX are merged into a single OP.

Please compare the relevant OPs carefully.

![image](https://user-images.githubusercontent.com/33194443/231643736-81286433-78c5-4f03-b786-c24273a2a583.png)

Therefore, even when no accuracy error actually occurs, there may be uncertainties in the accuracy verification.

As evidence of this, the subsequent verification of the OP's accuracy reduced the error to less than 1e-3. Note that the post-processing of R-CNN includes a number of indexing operations using integers, so it is inevitable that the absolute error due to a small error will appear large.

![image](https://user-images.githubusercontent.com/33194443/231644197-e003f479-1149-4257-9b13-29dc2f15f09f.png)
