### ISSUE TITLE
Can you convert onnx model with grid sample layer to tflite?

### ISSUE THREAD

**Issue by luan1412167** [PINTO0309/onnx2tf#39]
### Issue Type

Others

### onnx2tf version number

0.10.0

### Download URL for ONNX

None

### Parameter Replacement JSON

```json
None
```

### Description

Hi @PINTO0309,

Thanks for great repo. I want to ask can you convert a model with grid sample from pytorch to tflite?

Hope get your reply soon. Much thanks

**Comment by PINTO0309** [comment]
Please read the README first. And your version of onnx2tf is too old. The latest version as of today is v1.2.2.
https://github.com/PINTO0309/onnx2tf#supported-layers

![image](https://user-images.githubusercontent.com/33194443/205864489-bdd40deb-27ec-4c18-ae6b-b949db576c5e.png)

Because `grid_sample` has no means of straight conversion to TensorFlow, we have included an implementation that can handle only very limited situations. This tool is currently intended to support only Bilinear completion of 2D images, but it has not been fully tested, so conversion errors are likely to occur.

**Comment by PINTO0309** [comment]
No reply, so I'm closing.
