### ISSUE TITLE
Conversion gets stuck at tile operation

### ISSUE THREAD

**Issue by vedantdere** [PINTO0309/onnx2tf#425]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.11.5

### onnx version number

1.13.1

### onnxruntime version number

1.15.0

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.12.1

### Download URL for ONNX

[ONNX Model](https://drive.google.com/file/d/1_h8fkEvJu_IEIpNYhGYVzI0mJPX9u4AQ/view?usp=sharing)

### Parameter Replacement JSON

```json
I did not use this parameter replacement.
```

### Description

**First of all Thanks for awesome work.**
I wanted to make Thin Plate Spline Motion Model faster and which can be run on FP16 on cpu devices. Currently torch does not support fp16 for cpu. So I want to convert the model into tensorflow lite format so that I can use it in FP16.
`onnx2tf -i onnx_dense_optimized.onnx -b 1
`

**Logs**
[logs.txt](https://github.com/PINTO0309/onnx2tf/files/12169761/logs.txt)
The conversion is getting stuck at Tile operation 

**Screen shot** 
![Screenshot from 2023-07-26 13-07-43](https://github.com/PINTO0309/onnx2tf/assets/62639479/7cba9070-f137-4eeb-9d71-1d7435846a01)

**Thanks in advance for your effort reading, reacting and helping me. I really appreciate that!**

**Comment by PINTO0309** [comment]
The process is proceeding normally, just that the conversion is taking a very long time. The reason for this is the not-so-meaningful dimensional expansion process in the red rectangle in the figure below. The logic to compute the permutations with the least error after the transformation is implemented in `Tile`, but this `Tile` has too many dimensions. This cannot be excluded from the program because of the work-around process to eliminate transposition errors. 

Incidentally, approximately 518,400 patterns of transformations have been attempted to find the tensor arrangement with the smallest error among the 6Dx6D permutations.

Removing `Unsqueeze` and `Reshape` from the model would speed up the conversion.

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/c011a43c-2a38-4288-916c-cf41dea2590a)

**Comment by vedantdere** [comment]
**First of all Thank You soo much for giving your valuable time to solve the error** 
I have replaced the FlexMatrixInversion with torch.inverse and made custom ops in onnx and converted pytorch model to onnx 
[onnx_dense_optimized_inverse.zip](https://github.com/PINTO0309/onnx2tf/files/12173055/onnx_dense_optimized_inverse.zip)

I am having one question :- 
1] How you removed `unsqueeze` and `reshape` from the model to speed up ?

**Comment by PINTO0309** [comment]
Once again, TFLite does not support `Inverse`. `ONNX: Inverse -> TFLite: FlexMatrixInverse`
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/edd6f2b3-683a-4f0e-aabc-a2def38f2f9a)

>1] How you removed unsqueeze and reshape from the model to speed up ?

Since you did not provide the PyTorch code, I was forced to just rewrite the ONNX binary by hand.
1. https://github.com/PINTO0309/onnx2json
2. https://github.com/PINTO0309/json2onnx

**Comment by vedantdere** [comment]
ohh ok Thank you once again 
Instead of tflite can I use the keras model for inference ? I think the inverse issue is with the tflite only?

**Comment by PINTO0309** [comment]
It supports all formats, so try it yourself first.
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/2866f576-b931-4d69-a908-e3f7ec515700)
